In [2]:
import numpy as np
import torch

In [4]:
#create some random matrices
A=np.random.randn(3,4)
B=np.random.randn(4,5)
C=np.random.randn(3,7)

#try some multiplications
np.matmul(A,B)

#try some multiplications
print(np.round(A@B,2)), print(' ')
print(np.round(C.T@A,2))

[[ 3.31  4.72 -0.37 -1.38 -2.79]
 [-1.7   1.84 -1.63  0.12 -1.82]
 [ 1.87  2.9   0.1  -1.18 -2.02]]
 
[[-5.61 -0.45 -3.81 -0.89]
 [-0.87  0.82  0.06 -1.08]
 [ 3.75 -0.19  3.13  1.53]
 [ 6.48  0.27  4.32  1.34]
 [-2.4  -1.28 -3.76  0.17]
 [-1.58 -0.71 -1.66  0.3 ]
 [ 0.31 -0.05 -0.35 -0.1 ]]


In [5]:
#using torch

A=torch.randn(3,4)
B=torch.randn(4,5)
C1=np.random.randn(4,7)
C2=torch.tensor(C1, dtype=torch.float)

print(np.round(A@B,2)), print(' ')
print(np.round(A@C1,2)), print(' ')


tensor([[-0.9000, -0.6500,  0.9000,  0.8100, -2.6600],
        [ 0.1000,  0.8900,  0.1700, -0.4400, -0.5400],
        [-0.4000,  0.6300,  1.1000,  1.6300, -1.7200]])
 
tensor([[-0.9700,  1.2800,  1.3400,  0.5900,  2.4500, -0.2100,  1.7400],
        [-0.5500,  0.6100, -0.0300, -0.3700,  0.3500,  0.1500,  0.5000],
        [ 0.3900,  1.0100,  0.9000, -0.8100,  2.1400, -0.6500,  1.6600]],
       dtype=torch.float64)
 


C:\Users\Praditya\AppData\Local\Temp\ipykernel_17928\933888391.py:9: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  print(np.round(A@C1,2)), print(' ')


(None, None)