In [2]:
import numpy as np
import pandas
import torch

In [5]:
#create a vector
nv=np.array([[1,2,3,4]])
print(nv), print(' ')

#transpose it
print(nv.T),print(' ')

#transpose the transpose
nvT=nv.T
print(nvT.T)

[[1 2 3 4]]
 
[[1]
 [2]
 [3]
 [4]]
 
[[1 2 3 4]]


In [4]:
#repeat for matrix

nM=np.array([[1,2,3,4],[5,6,7,8]])
print(nM), print(' ')

#transposr it
print(nM.T),print(' ')

#transposre the transpose
nmT=nM.T
print(nmT.T),print(' ')

[[1 2 3 4]
 [5 6 7 8]]
 
[[1 5]
 [2 6]
 [3 7]
 [4 8]]
 
[[1 2 3 4]
 [5 6 7 8]]
 


(None, None)

In [6]:
#using pytorch
tv=torch.tensor([[1,2,3,4]])
print(tv),print(' ')

#transpose it
print(tv.T), print(' ')

#transpose the transpose
tvT=tv.T
print(tvT.T)


tensor([[1, 2, 3, 4]])
 
tensor([[1],
        [2],
        [3],
        [4]])
 
tensor([[1, 2, 3, 4]])
